### ISSUE TITLE
Check the console.

### ISSUE THREAD

**Issue by tgaeta** [HackerYou/SlackerYou#1]
Some errors preventing the chat from working.

![screen shot 2015-07-22 at 3 49 22 pm](https://cloud.githubusercontent.com/assets/9040988/8835576/5cd774a2-3089-11e5-95e0-8254ac0b03a0.png)

**Comment by wesbos** [comment]
Yeah I just grabbed the CSS from our main site - for some quick styling and one of the icon fonts isn't going cross-domain. Not something we are using for the chat room thoughl
